### ISSUE TITLE
weird sounding voices with MelGAN

### ISSUE THREAD

**Issue by gen35** [keonlee9420/Comprehensive-Transformer-TTS#6]
Hello,

Audio samples generated with multi-speaker MelGEN (haven't tried single-speaker) sound unnatural.

I know worse quality is expected, but all samples sound like having significantly too high pitch.

Maybe there is a bug in implementation ported from FastSpeech?

**Comment by keonlee9420** [comment]
Hi @gen35 , thanks for the report. Did you try HiFi-GAN for the inference as I did? If so, how was it different from MelGAN output? You also can have a try with the FastSpeech2 repo's demo with their pre-trained model and then see how it differs from yours. Please let me know the result since I need to update the project if there some issues from that.

**Comment by gen35** [comment]
I can confirm I'm getting similar results with original FastSpeech2.

I have no issues with HiFi-Gan. Compared to MelGan it sounds much more natural. 

I was thinking that maybe MelGan expects different format spectogram (It already takes mel/np.log(10)). But I'm not sure anymore.

**Comment by keonlee9420** [comment]
Close due to inactivity.
